# Complete Development Environment with Volume Mapping
# Run with: docker-compose -f docker-compose.dev.yml up
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: development
    container_name: pii-backend-dev
    ports:
      - "8000:8000"
    volumes:
      # Complete backend volume mapping
      - ./backend/src:/app/src                           # Source code hot reload
      - ./backend/package.json:/app/package.json:ro      # Package config
      - ./backend/package-lock.json:/app/package-lock.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro    # TypeScript config
      - ./backend/.env.example:/app/.env.example:ro      # Environment example
      # Anonymous volume for node_modules (performance)
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - USE_AWS_PROFILE=${USE_AWS_PROFILE:-false}
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    env_file:
      - .env
    networks:
      - pii-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: pii-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      # Complete frontend volume mapping
      - ./frontend/src:/app/src                          # Source code hot reload
      - ./frontend/public:/app/public                    # Static assets
      - ./frontend/package.json:/app/package.json:ro     # Package config
      - ./frontend/package-lock.json:/app/package-lock.json:ro
      - ./frontend/next.config.ts:/app/next.config.ts:ro # Next.js config
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts:ro # Tailwind config
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro   # TypeScript config
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs:ro # PostCSS config
      - ./frontend/components.json:/app/components.json:ro # shadcn/ui config
      # Anonymous volumes for performance
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true  # For better file watching in containers
    depends_on:
      - backend
    networks:
      - pii-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pii-network:
    driver: bridge

# Named volumes for better performance
volumes:
  backend_node_modules:
  frontend_node_modules:
  frontend_next_cache: